redhataccess/jwt-redhat

- package.json
- src/jwt.ts
- src/tokenUpdateScheduler.ts
Only update the token if the current tab is the master based on code adapted from https://blog.fastmail.com/2012/11/26/inter-tab-communication-using-local-storage/
> CPFED-1333: Implementing cross browser token update

- package.json
- src/index.d.ts
- src/jwt.ts
Using this new function to account for master/slave.
> implementing isTokenExpired

- package.json
- src/index.d.ts
- src/jwt.ts
- src/keycloak.ts
- src/localStorage.ts
- src/tokenUpdateScheduler.ts
Now broadcasting the token on the master token refresh to all slaves so that individual keycloak instances can be updated with the updated token.
> replicating the token to slaves

- README.md
- package.json
- src/index.d.ts
- src/jwt.ts
Modifying TTE to 58, fixing some bugs, and adding a new event to be called on the first successful token update.
> Updating TTE and new event 

- package.json
- src/jwt.ts
Allowing passing in the TTE to check against instead of just the default.
> adding param to isTokenExpired

- package.json
- src/cacheUtils.ts
- src/index.d.ts
- src/jwt.ts
Copying @mwcz implementation of a fail count for updating the token.  Also implementing callback events for onAuthRefreshError and onTokenExpired.
> Implementing a fail count

- package.json
- src/index.d.ts
- src/jwt.ts
- yarn.lock
This new callback allows parent apps to listen when the token successfully updated.
> PCM-6268: Implementing onAuthRefreshSuccess

- package.json
- src/jwt.ts
- src/keycloak.js
Keycloak.js did not properly set an error when the session states change.
> Properly setting error in keylcoak on not authenticated

- package.json
- src/index.d.ts
- src/jwt.ts
Change the fte url and also handle when the session mismatches to allow forcing a logout.
> Handling token mismatch

- package.json
- src/keycloak.js
http://cpfed-gitlab.usersys.redhat.com/customer-platform/cp-chrome/commit/23acc23e4213ff9c89811b55db2ad831f44a48f5
> Fixing hash redirect

- package.json
- src/index.d.ts
- src/jwt.ts
- src/models.ts
@engineersamuel Made changes as per our discussion.. Please review..
> Adding Basic Model for Internal Token

- package.json
- src/keycloak.js
There is a fix in the latest keycloak.js for handling session_state as a valid oauth param.
> PCM-6642: Upgrading keycloak.js

- package.json
- src/jwt.ts
@redhataccess/ascension-team Please review.
https://projects.engineering.redhat.com/browse/PCM-6792
> PCM-6792 - Jwt namespacing

- package.json
- src/jwt.ts
> More changes for segrigating token and namespacing

- package.json
- src/jwt.ts
> Keeping old cookie name

- package.json
- src/jwt.ts
@vrathee @gandhikeyur Please review.
I have removed cookie code from the project because we are not using this.
> Removed cookie from the jwt-redhat project .

- package.json
- src/jwt.ts
@vrathee @gandhikeyur Please review.
> fix origin error .

- package.json
- src/jwt.ts
@vrathee @gandhikeyur Please review.
> adding new event and cookie for the strata call .

- package.json
- src/index.d.ts
> update login method to return success .

- package.json
- src/index.d.ts
- src/jwt.ts
- src/models.ts
@vrathee @gandhikeyur Please review.
> skip redirect if user is logout from SSO-enabled service like PCM.

- package.json
- src/jwt.ts
- src/re-login-Iframe.html
>  Changed Broadcast channel polyfill and minor tweaks to reinit and logic

- @types/keycloak.d.ts
- package.json
- src/jwt.ts
- src/keycloak.js
> Pcm multi tab sync - remove old login frames

- src/jwt.ts
> Making sure we use the correct origin while deleting a cookie

- package.json
- src/jwt.ts
> Making sure token failure error is logged only once in sentry

- src/jwt.ts
> add attachment viewer qa and prod urls to generate correct sso url

- package.json
- src/jwt.ts
- tsconfig.json
- webpack.config.ts
- webpack.minified.config.ts
- webpack.unminified.config.ts
- yarn.lock
> Updating the sentry message in case token fails and resolved security warning in the repo

- src/jwt.ts
>  Adding duration to tag context instead of sentry message

- src/jwt.ts
- src/ssoUrlsEnum.ts
@vrathee @rh-kgarg @anujsi  please review.
> Updated auth urls for QA and dev envs. to point to stage as IAM has deprecated auth.dev and auth.qa services

- package-lock.json
- package.json
@vrathee @anujsi @rh-kgarg please review.
> marked localforage as  peer dependency

- src/jwt.ts
@vrathee @anujsi can you review this and merge
> Added connect prod and dev urls

- README.md
- src/jwt.ts
- src/models.ts
@vrathee @anujsi Please review.
> Passed env

- README.md
- src/index.d.ts
- src/index.ts
- src/models.ts
- src/ssoEnvEnum.ts
- src/ssoUrlsEnum.ts
> Added Sso Environments as Enums

- .npmignore
- src/jwt.ts
@akshygupt @vrathee Please review.
> remover personal details from the sentry .

- src/index.ts
@ppareekh Please review.
Minor change.
> Export getSsoUrl function .

- src/index.d.ts
@adithyaakrishna Please review.
> Export getSsoUrl function in the types file .
